/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 22 05:43:59 GMT 2019
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.FizzBuzz2;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FizzBuzz2_ESTest extends FizzBuzz2_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FizzBuzz2 fizzBuzz2_0 = new FizzBuzz2();
      // Undeclared exception!
      try { 
        fizzBuzz2_0.fizzBuzz(0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tutorial.FizzBuzz2", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FizzBuzz2 fizzBuzz2_0 = new FizzBuzz2();
      String string0 = fizzBuzz2_0.fizzBuzz(3);
      assertEquals("Fizz", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FizzBuzz2 fizzBuzz2_0 = new FizzBuzz2();
      String string0 = fizzBuzz2_0.fizzBuzz(1160);
      assertEquals("Buzz", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FizzBuzz2 fizzBuzz2_0 = new FizzBuzz2();
      String string0 = fizzBuzz2_0.fizzBuzz(225);
      assertEquals("FizzBuzz", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FizzBuzz2 fizzBuzz2_0 = new FizzBuzz2();
      // Undeclared exception!
      try { 
        fizzBuzz2_0.fizzBuzz((-2476));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tutorial.FizzBuzz2", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FizzBuzz2 fizzBuzz2_0 = new FizzBuzz2();
      String string0 = fizzBuzz2_0.fizzBuzz(1238);
      assertEquals("1238", string0);
  }
}
