/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 22 05:37:43 GMT 2019
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.FizzBuzz1;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FizzBuzz1_ESTest extends FizzBuzz1_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FizzBuzz1 fizzBuzz1_0 = new FizzBuzz1();
      // Undeclared exception!
      try { 
        fizzBuzz1_0.fizzBuzz(0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tutorial.FizzBuzz1", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FizzBuzz1 fizzBuzz1_0 = new FizzBuzz1();
      String string0 = fizzBuzz1_0.fizzBuzz(5);
      assertEquals("Buzz", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FizzBuzz1 fizzBuzz1_0 = new FizzBuzz1();
      String string0 = fizzBuzz1_0.fizzBuzz(2);
      assertEquals("2", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FizzBuzz1 fizzBuzz1_0 = new FizzBuzz1();
      String string0 = fizzBuzz1_0.fizzBuzz(1758);
      assertEquals("Fizz", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FizzBuzz1 fizzBuzz1_0 = new FizzBuzz1();
      // Undeclared exception!
      try { 
        fizzBuzz1_0.fizzBuzz((-34));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tutorial.FizzBuzz1", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FizzBuzz1 fizzBuzz1_0 = new FizzBuzz1();
      String string0 = fizzBuzz1_0.fizzBuzz(60);
      assertEquals("FizzBuzz", string0);
  }
}
